language: python
python:
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=postgres
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - nosetests --with-coverage
after_success: coveralls
cache: pip