"""empty message

Revision ID: 98b2d88510bc
Revises: d367a58871b8
Create Date: 2018-02-17 13:12:17.053393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b2d88510bc'
down_revision = 'd367a58871b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
