"""empty message

Revision ID: d367a58871b8
Revises: 
Create Date: 2017-06-28 14:22:54.373637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd367a58871b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketlists_owner_id_fkey', 'bucketlists', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlists', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.create_foreign_key('bucketlists_owner_id_fkey', 'bucketlists', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
